// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Ajax: typeof import('./src/components/Ajax.vue')['default']
    Ajax2: typeof import('./src/components/Ajax2.vue')['default']
    Count: typeof import('./src/components/Count.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
